var bandcamp = require('../lib/index');

var fanUrl = 'https://bandcamp.com/namtah';
bandcamp.getFanInfo(fanUrl, function(error, fanInfo) {
  if (error) {
    console.log(error);
  } else {
    console.log(JSON.stringify(fanInfo, null, 4));
  }
});

/*
{
    "trackpipe_url": "https://bandcamp.com/namtah",
    "username": "namtah",
    "name": "NAMTAH",
    "fan_id": 472496,
    "location": "Georgia",
    "raw_location": "Georgia, USA",
    "bio": null,
    "website_url": null,
    "is_own_page": null,
    "followers_count": 1,
    "following_bands_count": 9,
    "following_fans_count": 8,
    "subscriptions_count": 0,
    "fanbiopic": "https://f4.bcbits.com/img/0004634639_41.jpg",
    "collection": [
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 250,
            "release_count": null,
            "why": "...love the concept as much as the music...",
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 426515167,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 31048744,
            "item_id": 126707477,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 126707477,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://store.bravewave.net/album/heart-beat-circuit?t=7",
            "band_id": 4008044529,
            "tralbum_id": 126707477,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 10,
            "band_location": null,
            "item_url": "http://store.bravewave.net/album/heart-beat-circuit",
            "url_hints": {
                "custom_domain_verified": 1,
                "subdomain": "bravewave",
                "item_type": "a",
                "custom_domain": "store.bravewave.net",
                "slug": "heart-beat-circuit"
            },
            "featured_track_title": "Mirror Pool (ft. Takahiro Izutani)",
            "item_title": "Heart Beat Circuit",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3869736399,
            "band_name": "Smoke Thief"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": false,
            "is_private": false,
            "also_collected_count": 1720,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 1925685198,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 31517447,
            "item_id": 670668694,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 670668694,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": null,
            "band_id": 1916175907,
            "tralbum_id": 670668694,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 4,
            "band_location": null,
            "item_url": "http://inlovewithaghost.bandcamp.com/album/lets-go",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "inlovewithaghost",
                "item_type": "a",
                "custom_domain": null,
                "slug": "lets-go"
            },
            "featured_track_title": "we've never met but, can we have a coffee or something",
            "item_title": "let's go",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3234590170,
            "band_name": "In Love With A Ghost"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 683,
            "release_count": null,
            "why": "A pirate's heart can be beautiful. Listen and see...",
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 1328452291,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 43520227,
            "item_id": 838845289,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 838845289,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://musique.coeurdepirate.com/album/blonde?t=7",
            "band_id": 2534369253,
            "tralbum_id": 838845289,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 12,
            "band_location": null,
            "item_url": "http://musique.coeurdepirate.com/album/blonde",
            "url_hints": {
                "custom_domain_verified": 1,
                "subdomain": "coeurdepirate",
                "item_type": "a",
                "custom_domain": "musique.coeurdepirate.com",
                "slug": "blonde"
            },
            "featured_track_title": "Les amours dévouées",
            "item_title": "Blonde",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 4086570201,
            "band_name": "Cœur de pirate"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": false,
            "is_private": false,
            "also_collected_count": 393,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 1794321756,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": null,
            "item_id": 858692736,
            "gift_sender_note": null,
            "is_subscription_item": null,
            "is_subscriber_only": false,
            "album_id": 858692736,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": null,
            "band_id": 621468927,
            "tralbum_id": 858692736,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 14,
            "band_location": null,
            "item_url": "http://brokeforfree.bandcamp.com/album/petal",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "brokeforfree",
                "item_type": "a",
                "custom_domain": "brokeforfree.com",
                "slug": "petal"
            },
            "featured_track_title": "Golden Hour",
            "item_title": "Petal",
            "sale_item_type": null,
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 1840733221,
            "band_name": "Broke For Free"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 1201,
            "release_count": null,
            "why": "...soon, I will chill...",
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 3393643952,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 21160709,
            "item_id": 1154278922,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 1154278922,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://emancipator.bandcamp.com/album/soon-it-will-be-cold-enough?t=6",
            "band_id": 3748196749,
            "tralbum_id": 1154278922,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 12,
            "band_location": null,
            "item_url": "http://emancipator.bandcamp.com/album/soon-it-will-be-cold-enough",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "emancipator",
                "item_type": "a",
                "custom_domain": "soonitwillbecoldenough.emancipatormusic.com",
                "slug": "soon-it-will-be-cold-enough"
            },
            "featured_track_title": "smoke signals",
            "item_title": "soon it will be cold enough",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3365359639,
            "band_name": "emancipator"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 367,
            "release_count": null,
            "why": "...my motivational relaxation music...haunting and uplifting at once...",
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 1019615575,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 21146919,
            "item_id": 2056179457,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 2056179457,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://music.tomday.me/album/tom-day-2012-collection?t=11",
            "band_id": 412091201,
            "tralbum_id": 2056179457,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 11,
            "band_location": null,
            "item_url": "http://music.tomday.me/album/tom-day-2012-collection",
            "url_hints": {
                "custom_domain_verified": 1,
                "subdomain": "tomday",
                "item_type": "a",
                "custom_domain": "music.tomday.me",
                "slug": "tom-day-2012-collection"
            },
            "featured_track_title": "Tom Day - Love Your Life",
            "item_title": "Tom Day - 2012 Collection",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 2852711381,
            "band_name": "Tom Day"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 74,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 3365430288,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 41005338,
            "item_id": 2354846185,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 2354846185,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://kinack.bandcamp.com/album/ondas?t=3",
            "band_id": 18199703,
            "tralbum_id": 2354846185,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 14,
            "band_location": null,
            "item_url": "http://kinack.bandcamp.com/album/ondas",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "kinack",
                "item_type": "a",
                "custom_domain": null,
                "slug": "ondas"
            },
            "featured_track_title": "Idea for a Brand New World",
            "item_title": "Ondas",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3080279293,
            "band_name": "Kinack"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": false,
            "is_private": false,
            "also_collected_count": 58,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 3032817640,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": null,
            "item_id": 2509298207,
            "gift_sender_note": null,
            "is_subscription_item": null,
            "is_subscriber_only": false,
            "album_id": 2509298207,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": null,
            "band_id": 672739759,
            "tralbum_id": 2509298207,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 8,
            "band_location": null,
            "item_url": "http://theseknottylines.bandcamp.com/album/unreliable-narrator",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "theseknottylines",
                "item_type": "a",
                "custom_domain": null,
                "slug": "unreliable-narrator"
            },
            "featured_track_title": "Shiny Destination",
            "item_title": "Unreliable Narrator",
            "sale_item_type": null,
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3819679679,
            "band_name": "the rutabega"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": false,
            "is_private": false,
            "also_collected_count": 5,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 4058604018,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": null,
            "item_id": 2545299968,
            "gift_sender_note": null,
            "is_subscription_item": null,
            "is_subscriber_only": false,
            "album_id": 2545299968,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": null,
            "band_id": 3901025918,
            "tralbum_id": 2545299968,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 8,
            "band_location": null,
            "item_url": "http://wakhan.bandcamp.com/album/mystical-encounter-with-yourself",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "wakhan",
                "item_type": "a",
                "custom_domain": null,
                "slug": "mystical-encounter-with-yourself"
            },
            "featured_track_title": "A.I. Data Fields",
            "item_title": "Mystical Encounter With Yourself",
            "sale_item_type": null,
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 1371216106,
            "band_name": "Wakhan"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 16,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 1884821593,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 35375336,
            "item_id": 2671522961,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 2671522961,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://ionomusic.bandcamp.com/album/chill-out-realms?t=3",
            "band_id": 3782870952,
            "tralbum_id": 2671522961,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 10,
            "band_location": null,
            "item_url": "http://ionomusic.bandcamp.com/album/chill-out-realms",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "ionomusic",
                "item_type": "a",
                "custom_domain": null,
                "slug": "chill-out-realms"
            },
            "featured_track_title": "Bombay Day Trip",
            "item_title": "Chill Out Realms",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3166270628,
            "band_name": "Motion Drive"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 898,
            "release_count": null,
            "why": "Tycho's music - I could sit and watch it all day!",
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 978734060,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 33500783,
            "item_id": 3619628392,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 3619628392,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://tycho.bandcamp.com/album/dive?t=9",
            "band_id": 338921882,
            "tralbum_id": 3619628392,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 10,
            "band_location": null,
            "item_url": "http://tycho.bandcamp.com/album/dive",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "tycho",
                "item_type": "a",
                "custom_domain": null,
                "slug": "dive"
            },
            "featured_track_title": "Epigram",
            "item_title": "Dive",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 1153728839,
            "band_name": "Tycho"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": false,
            "is_private": false,
            "also_collected_count": 484,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 3117727530,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 39953784,
            "item_id": 3983318487,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 3983318487,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": null,
            "band_id": 292199932,
            "tralbum_id": 3983318487,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 14,
            "band_location": null,
            "item_url": "http://ghostdata.bandcamp.com/album/girls-love",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "ghostdata",
                "item_type": "a",
                "custom_domain": null,
                "slug": "girls-love"
            },
            "featured_track_title": "Silk Lingerie",
            "item_title": "Girl's Love 少女愛",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 3904197104,
            "band_name": "GHOST DATA"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": false,
            "is_private": false,
            "also_collected_count": 25,
            "release_count": null,
            "why": null,
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 2547690984,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": null,
            "item_id": 4105182012,
            "gift_sender_note": null,
            "is_subscription_item": null,
            "is_subscriber_only": false,
            "album_id": 4105182012,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": null,
            "band_id": 348545416,
            "tralbum_id": 4105182012,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 6,
            "band_location": null,
            "item_url": "http://yeule.bandcamp.com/album/pathos",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "yeule",
                "item_type": "a",
                "custom_domain": null,
                "slug": "pathos"
            },
            "featured_track_title": "Desire",
            "item_title": "pathos",
            "sale_item_type": null,
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 2669403601,
            "band_name": "yeule"
        },
        {
            "band_image_id": null,
            "featured_track_is_custom": true,
            "is_private": false,
            "also_collected_count": 299,
            "release_count": null,
            "why": "Good stuff...",
            "item_type": "album",
            "is_giftable": true,
            "item_art_id": 1000991114,
            "tralbum_type": "a",
            "message_count": null,
            "sale_item_id": 23530058,
            "item_id": 4266094580,
            "gift_sender_note": null,
            "is_subscription_item": false,
            "is_subscriber_only": false,
            "album_id": 4266094580,
            "package_details": null,
            "service_url_fragment": null,
            "featured_track_url": "http://yukari.bandcamp.com/album/echo?t=9",
            "band_id": 913556034,
            "tralbum_id": 4266094580,
            "service_name": null,
            "gift_sender_name": null,
            "num_streamable_tracks": 10,
            "band_location": null,
            "item_url": "http://yukari.bandcamp.com/album/echo",
            "url_hints": {
                "custom_domain_verified": null,
                "subdomain": "yukari",
                "item_type": "a",
                "custom_domain": null,
                "slug": "echo"
            },
            "featured_track_title": "09 Where Do I Go?*Bonus track_only released in Japan",
            "item_title": "Echo",
            "sale_item_type": "p",
            "gift_recipient_name": null,
            "gift_id": null,
            "hidden": null,
            "is_purchasable": true,
            "featured_track": 2123718480,
            "band_name": "유카리(Yukari)"
        }
    ]
}

*/
